export const Strings = {
  introSliderOneHeaderContent: `Welcome,${`\n`} Psychonaut`,
  introSliderOneSubContent:
    "Enhance your psychedelic practice by measuring your psycho-spiritual progress.",
  introSliderTwoHeaderContent: "Meet Lucy",
  introSliderTwoSubContent:
    "Gain insights into how your psychedelic use affects your overall well-being. ",
  introSliderThreeHeaderContent: "We are psychonaut scientists on a mission",
  introSliderThreeSubContent:
    "To advance the understanding of psychedelic cognition.",
  signUp: "Sign up",
  signUpSubContent:
    "You have the chance to create new account, if you really want to.",
  fullName: "Full Name",
  emailAddress: "Email address",
  createNewPassword: "Create new password ",
  confirmPassword: "Confirm password",
  alreadyAccount: "Already have account?",
  goHere: "Go here",
  PrivacyFooterContent: `Your privacy is of utmost importance to our community, don't worry all your data is anonymized and will NEVER be sold to a third party.`,
  verificationCode: "Verification Code",
  verifySubContent: `We have sent the verification ${"\n"} code to your email.`,
  verify: "Verify",
  didNotReceive: "Didn’t receive one?",
  getNewCode: "Get new code.",
  membershipHeadingContent: "Get Free Psychedelic Insights For a Year",
  joinMembershipContent: "Join your fellow psychonauts ",
  memberShipFooterContentOne: `One year free, then $34.99/year ${"\n"} starting April 30, 2022.`,
  memberShipFooterContentTwo: `Cancel any time through your ${"\n"} phone Account Settings.`,
  termsCondition: "Terms & Conditions",
  privacyPolicy: "Privacy Policy",
  thanksForJoining: "Thanks for Joining!",
  joiningWelcomeContent: "Welcome fellow psychonaut",
  trackDataBoldHeadingContent: "Based on your current iPhone software, ",
  trackDataHeadingContent: "we are required to ask you to track certain data.",
  notNow: "Not Now",
  notificationHeadingContent: `Would you like to ${`\n`} receive notifications?`,
  notificationSubContentOne: `Enable notification to get updates ${`\n`} on your progress.`,
  notificationSubContentTwo: `We will let you know when you ${`\n`} have added anough data points to ${`\n`} yield results.`,
  resetPassword: "Reset Password",
  createAccount: "Create new account",
  forgotPasswordHeadingContent: "Forgot your Password?",
  passwordSubContent: "Lorem ipsum dolor etes the sum need a new password",
  typeEmail: "Type your email",
  enterPassword: "Enter your password",
  success: "Success!",
  resetPasswordSuccess: "You have reset your password.",
  login: "Login",
  doseHeadingContent: "Thanks for adding that!",
  doseSubContentOne: `If you have time now let’s start with ${`\n`} your first journal entry.`,
  doseSubContentTwo: `The more journal entries you add, the ${`\n`} better I will be able to show you how ${`\n`} your psychedelic use is affecting you ${`\n`} overtime.`,
  onboardingTwoHeadingContent:
    "Can you tell us a little bit about your past psychedelic use?",
  heroDoseOptionHeadingContent: "Select all psychedelics you have hero dosed.",
  searchPsychedelics: "Search psychedelics",
  microDosedOptionHeadingContent:
    "Select all psychedelics you have microdosed.",
  trackFirstTimeHeadingContent:
    "Why track your interactions with pyschedelics?",
  trackFirstTimedetailContent: `By keeping a detailed journal of ${`\n`} your psychedelic habits we can ${"\n"} help you discover how your ${"\n"} cognitive, emotional and spiritual ${"\n"} habits change overtime.`,
  trackHeading: "Track Your Dose",
  trackDescription:
    "Keep up the good work! The more data you provide, the more accurate your results will be. ",

  // Home
  welcome: "Welcome!",
  jaclyn: "Jaclyn",
  insights: "Insights",
  homeFirstBoxContain: `Data needed! Record more ${`\n`} entries to unlock insights.`,
  trackNow: "Track Now",
  recordLastDose: "Record last dose",
  journalHistory: "Journal History",
  newMicroDosing: "New to microdosing?",
  HomeFourthBoxContain: "Checkout Laura Dawn’s Free Microdosing Course",
  meetLucy: " Meet Lucy: Our Why",
  thanksFor: "Thanks for being here!",
  needHelp: `Need help? Send me an email at mailto:help@lucyapp.ai`,
  myJournal: "My Journal ",
  newJournal: "New Journal",
  viewEntries: "View Entries",
  newJournalEntry: "New Journal Entry ",
  recordAudio: "Record Audio Journal ",
  writeTextJournal: "Write Text Journal",
  feelingHeadingContain: "How do you feel?",
  feelingSubContain: `On a scale from 1 being bad ${`\n`} to 10 being great.`,
  submit: "Submit",
  readyRecordAudio: "Ready to record?",
  inProgressRecordAudio: "In Progress...",
  playAudio: "Play Audio",
  maxAudioTime: "Max recording time: 10 minutes.",
  editViewButtonText: "View/Edit Recording",
  save: "SAVE",
  allDone: "All done!",
  viewJournals: "View My Journals",
  myJournals: "My Journals",
  recording: "Recording 1",
  textJournal: "Text Journal",
  listenRecording: "Listen to your recording",
  viewEditTranscription: "View/edit transcription",
  viewEditJournal: "View/edit journal",
  selectDateRange: "Select Date Range",
  yes: "Yes",
  addYourFirstJournalEntry: "Add your first journal entry",
  startMembership: "Start Membership",
  saveDate: "Save Date",

  signIn: "Sign in",
  sendReset: "Send reset",

  myJourney: "My Journey",
  insights: "Insights ",
  psychedelicActivity: "Psychedelic Activity",
  journalingHistory: "Journaling  History",

  thankyouHeading: "Thanks for tracking!",
  thankyouDesc:
    "Now that you're done tracking, tell me about your experience taking LSD.",

  //New 21-12

  reportedMood: `Reported ${`\n`}Mood`,
  psychedelicExperiences: `Psychedelic${`\n`}Experiences`,
  insightsHeading: `On average, your mood is positively correlated with psychedelic use. With an average score of 80%.`,
  yourAverageMood: "Your Average Mood",
  selfReported: "self reported after taking psychedelic",
  feelingBest: "When Was I Feeling Best?",
  theInBetween: "The In Between",
  theBetweenSubContent:
    "It all started with a glimmering light in the corner of the room asn as I...",
  feelingWorst: "When Was I Feeling Worst?",
  onceUponTime: "Once Upon a Time",
  onceUponTimeSubContent:
    "We all laid down in a friends living room listening to soft music wait...",

  totalDoses: "Total Doses",
  microDoses: "Microdoses",
  MacroDoses: "Macrodoses",
  including: "Including:",
  pscilocybin: "Pscilocybin",
  ayahuaska: "Ayahuaska",
  psilocybin: "Psilocybin",
  lastUsed: "Last Used",
  dayAgo: "a day ago",
  mostCommonDose: "Most common dose",

  //

  journalingHistory: `Journaling${`\n`}History`,
  journalEntries: `Journal${"\n"}Entries`,
};
